### ISSUE TITLE
Regex doesn't properly detect enabled services

### ISSUE THREAD

**Issue by k8r-io** [GeoffWilliams/chsubserver#1]
The current $op_match for ensure=>disabled doesn't work right.

Let's say I have a inetd.conf with talk disabled and ntalk enabled, and I'd like to ensure disabled for both

```
#talk   dgram   udp     wait    root    /usr/sbin/talkd talkd
ntalk       dgram   udp     wait    root    /usr/sbin/talkd talkd
```

The regex match for disabling talk would, effectively, be /^[^#].*talk.*/ which will match the second line since n is not #.  So, so long as ntalk is not disabled puppet will try to disable the already disabled talk. Not the biggest issue in an of itself; however, when it goes to evaluate ntalk being disable the regex is /^[^#].*ntalk.*/ and it will never match the second line, unless there is whitespace stuck before it.

This can be helpful when trying to test regex
https://www.online-utility.org/text/grep.jsp

**Comment by GeoffWilliams** [comment]
https://github.com/GeoffWilliams/chsubserver/pull/2 has been merged - anyone with an AIX box able to confirm correct operation for me? - thanks!

**Comment by GeoffWilliams** [comment]
presumed working
